<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_firstNameLastNameInBillingAddress</name>
   <tag></tag>
   <elementGuidId>f60e52da-85d9-40fd-b2fc-2883bb9cc08d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id=&quot;address_invoice&quot;]//li[contains(@class,'address_firstname')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
